version: '3'
services:
  django:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    env_file:
      - .env
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

  db:
    image: postgres:16
    container_name: app_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
