# Generated by Django 4.2.11 on 2024-06-13 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genrefilmwork",
            options={
                "verbose_name": "Жанры и кинопроизведения",
                "verbose_name_plural": "Жанров и кинопроизведений",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Актер", "verbose_name_plural": "Актеры"},
        ),
        migrations.AlterModelOptions(
            name="personfilmwork",
            options={
                "verbose_name": "Актер и кинопроизведения",
                "verbose_name_plural": "Актеры и кинопроизведения",
            },
        ),
        migrations.AddField(
            model_name="filmwork",
            name="genres",
            field=models.ManyToManyField(
                through="movies.GenreFilmWork", to="movies.genre"
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="rating",
            field=models.FloatField(
                blank=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
