# Generated by Django 4.2.11 on 2024-06-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_genrefilmwork_options_alter_person_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={
                "verbose_name": "Кинопроизведения",
                "verbose_name_plural": "Кинопроизведения",
            },
        ),
        migrations.AddField(
            model_name="filmwork",
            name="certificate",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Certificate"
            ),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.FileField(
                blank=True, null=True, upload_to="movies/", verbose_name="File"
            ),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="persons",
            field=models.ManyToManyField(
                through="movies.PersonFilmWork", to="movies.person"
            ),
        ),
    ]
