# Generated by Django 4.2.11 on 2024-06-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_filmwork_options_filmwork_certificate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={"verbose_name": "Film work", "verbose_name_plural": "Film works"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Genre", "verbose_name_plural": "Genres"},
        ),
        migrations.AlterModelOptions(
            name="genrefilmwork",
            options={
                "verbose_name": "Genre and film",
                "verbose_name_plural": "Genres and films",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Actor", "verbose_name_plural": "Actors"},
        ),
        migrations.AlterModelOptions(
            name="personfilmwork",
            options={
                "verbose_name": "Actor and film work",
                "verbose_name_plural": "Actors and film works",
            },
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="type",
            field=models.CharField(
                choices=[("фильм", "Movie"), ("тв шоу", "Tv Show")],
                default="фильм",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
