# Generated by Django 4.2.11 on 2024-06-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_filmwork_certificate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genrefilmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="personfilmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="genrefilmwork",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="personfilmwork",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
