# Generated by Django 4.2.11 on 2024-06-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_rename_created_genrefilmwork_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="creation_date",
            field=models.DateField(blank=True, null=True, verbose_name="Creation Date"),
        ),
    ]
