# Generated by Django 4.2.11 on 2024-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0010_alter_genre_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
