# Generated by Django 4.2.11 on 2024-06-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0011_alter_filmwork_updated_at_alter_genre_updated_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("genre", "film_work"), name="unique_genre_film_work"
            ),
        ),
    ]
