# Generated by Django 4.2.11 on 2024-06-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0012_genrefilmwork_unique_genre_film_work"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                fields=("person", "film_work", "role"), name="unique_person_film_work"
            ),
        ),
    ]
