# Generated by Django 4.2.11 on 2024-06-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0013_personfilmwork_unique_person_film_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
