# Generated by Django 4.2.11 on 2024-07-03 05:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0014_alter_filmwork_created_at_alter_genre_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filmwork",
            old_name="genres",
            new_name="genres_for_films",
        ),
    ]
